server:
    port: 8888

spring:
    ai:
        ollama:
            base-url: http://localhost:11434
            chat:
                model: qwen2.5:14b

app:
    cors:
        allowed-origins:
            - http://localhost:5173
            - http://localhost:5174
            - http://localhost:3000

logging:
    level:
        com.example: DEBUG