server:
    port: 8888

spring:
    ai:
        ollama:
            base-url: http://localhost:11434
            chat:
                model: qwen2.5:14b

app:
    cors:
        allowed-origins:
            - "*"

logging:
    level:
        com.example: DEBUG